version: 0.1.{build}-{branch}
platform:
  - x64
os: Visual Studio 2015
matrix:
  fast_finish: false
skip_tags: true
build: off
init:
- set CONDA=C:\Miniconda36-x64
- set PATH=%CONDA%;%CONDA%\Scripts;%CONDA%\Library\bin;C:\Rust\bin;%PATH%

environment:
  matrix:
    - CHANNEL: 1.40.0
      H5_VERSION: 1.8.21
      H5_SOURCE: msi
    - CHANNEL: beta
      H5_VERSION: 1.10.0
      H5_SOURCE: msi
      H5_PIN: yes
    - CHANNEL: nightly
      H5_VERSION: 1.10.4
      H5_SOURCE: conda

install:
  - python ci\appveyor.py install-rust
  - python ci\appveyor.py install-hdf5

test_script:
  - python ci\appveyor.py run-tests
