[package]
name = "hdf5-sys"
version = "0.6.1"  # !V
authors = ["Ivan Smirnov <i.s.smirnov@gmail.com>"]
keywords = ["hdf5"]
license = "MIT/Apache-2.0"
build = "build.rs"
repository = "https://github.com/aldanor/hdf5-rust"
homepage = "https://github.com/aldanor/hdf5-rust"
description = "Native bindings to the HDF5 library."
edition = "2018"

[dependencies]
libc = "0.2"
mpi-sys = { version = "0.1", optional = true }

[features]
default = []
mpio = ["mpi-sys"]
# Use static HDF5 libs downloaded from conda.
conda = []

[build-dependencies]
libloading = "0.6"
md5 = "0.6"
attohttpc = { version = "0.12", default-features = false, features = ["compress", "tls-rustls"] }
bzip2 = "0.3.3"
tar = "*"
regex = { version = "1.3", features = ["std"] }

[target.'cfg(all(unix, not(target_os = "macos")))'.build-dependencies]
pkg-config = "0.3"

[target.'cfg(windows)'.build-dependencies]
serde = "1.0"
serde_derive = "1.0"
winreg = { version = "0.7", features = ["serialization-serde"]}
