[package]
name = "hdf5-types"
version = "0.6.1"  # !V
authors = ["Ivan Smirnov <i.s.smirnov@gmail.com>"]
keywords = ["hdf5"]
license = "MIT/Apache-2.0"
description = "Native Rust equivalents of HDF5 types."
repository = "https://github.com/aldanor/hdf5-rust"
homepage = "https://github.com/aldanor/hdf5-rust"
edition = "2018"

[dependencies]
ascii = "1.0"
libc = "0.2"

[dev-dependencies]
quickcheck = { version = "0.9", default-features = false }
unindent = "0.1"